### ISSUE TITLE
clarify usage of in/excludingLabels

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#119]
https://github.com/Half-Shot/matrix-hookshot/blob/e6dd83ac5bd57a9e189b74999879efb767331646/docs/usage/room_configuration/github_repo.md#L33-L34

implies there can be multiple labels each, but value is supposed to be a string?

what is the string delimiter? should it be a list of strings?

**Comment by Half-Shot** [comment]
This should be an array of strings.

**Comment by Half-Shot** [comment]
Fixed in https://github.com/Half-Shot/matrix-hookshot/commit/f452cc7ed2d1f09a70d5a5ae2c3eb538f9466e20
