### ISSUE TITLE
generic webhooks + markdown, and docs

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#123]
if I receive a "generic" webhook without jstransform stuff, would it be a plain m.text without formatting? it says that markdown is rendered after jstransform if you use them.
> If the body contains a `text` key, then that key will be used as a message body in Matrix.
> result will be automatically transformed by a Markdown parser.

I would find it very useful to send json with a `formatted_text` key which would be used literally as `formatted_body` of a org.matrix.custom.html message. is markdown applied to `text`?
> If the body also contains a `username` key, then the message will be prepended by the given username.

so, like a relaybot bridge? would be nice to have "puppeting" this way, as matrix-appservice-webhooks used to

**Comment by HarHarLinks** [comment]
@Half-Shot thoughts about my feature request?

> send json with a `formatted_text` key which would be used literally as `formatted_body` of a org.matrix.custom.html message

i.e. send html preformatted to the webhook instead of markdown

**Comment by Half-Shot** [comment]
Totally missed that, sounds reasonable to me! Can you create a separate issue for the feature request?
