### ISSUE TITLE
document to which listener the oauth endpoints belong

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#131]
existing doc:
https://github.com/Half-Shot/matrix-hookshot/blob/9030581de2739e721475e6d0bac8725f973ed04b/docs/setup.md#L93-L95
https://github.com/Half-Shot/matrix-hookshot/blob/9030581de2739e721475e6d0bac8725f973ed04b/docs/setup.md#L117

missing:
https://github.com/Half-Shot/matrix-hookshot/blob/9030581de2739e721475e6d0bac8725f973ed04b/docs/setup/jira.md#L31
https://github.com/Half-Shot/matrix-hookshot/blob/9030581de2739e721475e6d0bac8725f973ed04b/docs/setup/github.md#L74

**Comment by Half-Shot** [comment]
Fixed by #132
