### ISSUE TITLE
clarify passkey.pem location

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#133]
there exists this config option
https://github.com/Half-Shot/matrix-hookshot/blob/cdd05e7aebaffc20030dab1642bfa4559cb5f816/config.sample.yml#L65

the workdir of docker is
https://github.com/Half-Shot/matrix-hookshot/blob/cdd05e7aebaffc20030dab1642bfa4559cb5f816/Dockerfile#L25

should the config with docker be `passFile: /data/passkey.pem`? or should it be mounted somewhere else?

**Comment by Half-Shot** [comment]
I'd expect `/data/passkey.pem` for a docker install yeah.

**Comment by HarHarLinks** [comment]
so with docker, I keep a simple `passkey.pem` in config.yml and put it in the directory that is mounted to `/data/`? sorry, your reply still isn't entirely clear to me 😅

**Comment by Half-Shot** [comment]
Yep, so your file structure would be

- / 
  - /data
    - /data/config.yml
    - /data/passkey.pem

and your config file would reference /data/passkey.pem
