### ISSUE TITLE
Help commands aren't aware of which integrations are configured

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-hookshot#138]
This instance is only configured for GitHub and nothing else:

![image](https://user-images.githubusercontent.com/1190097/148704892-66109bbc-9feb-43cf-b674-4955fcc79937.png)

![image](https://user-images.githubusercontent.com/1190097/148704922-42cc2fbc-e565-4fcc-9adf-e4c2d544a9d5.png)

**Comment by Half-Shot** [comment]
Yep, this basically needs the bot command handler to support toggling commands based on config. Should be fairly straightforward to do.
