### ISSUE TITLE
jira docs issues

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#146]
https://github.com/Half-Shot/matrix-hookshot/blob/0c4b911a705f464d0a1edb51b2181845c4894b14/docs/setup/jira.md#L28-L32

looks like

![image](https://user-images.githubusercontent.com/2803622/148849612-1b69ee0a-a563-4d68-b669-3f49989ae737.png)

---

https://github.com/Half-Shot/matrix-hookshot/blob/e66d1ef2e18431611130417360f803846b4ed894/docs/setup/jira.md#L48

what capabilities?

**Comment by Half-Shot** [comment]
ugh, markdown.
