### ISSUE TITLE
update github docs

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#148]
https://github.com/Half-Shot/matrix-hookshot/blob/2a676afca0c75bae2eb5090f4cfaf1421f053279/docs/setup/github.md#L23

These are apparently called "Team discussions", which gave me a pause looking for them. Is just "read" correct, vs Repo Discussions r&w?

---

https://github.com/Half-Shot/matrix-hookshot/blob/2a676afca0c75bae2eb5090f4cfaf1421f053279/docs/setup/github.md#L10

This means after creating the app, click "generate client secret". But actually only when using OAuth?

At this point it should be added that you need to scroll down to private keys, generate and download one, then set `privateKeyFile` to its path. Also please add that with docker, one should once more use `/data/$filename` if that's correct.

**Comment by Half-Shot** [comment]
I've removed that bullet point list at the top as I think it was confusing and added instructions to the relevant sections.
