### ISSUE TITLE
span tags with data-mx-bg-color, data-mx-color, title are ignored on android, leaving labels unintelligible

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#151]
```
"formatted_body": "Half-Shot created new issue <a href=\"https://github.com/Half-Shot/matrix-hookshot/issues/139\">Half-Shot/matrix-hookshot#139</a>: &quot;If a PR/MR is closed with a comment, append that comment to the closed message.&quot; with labels <span data-mx-bg-color=\"#a2eeef\" data-mx-color=\"#000000\" title=\"New feature or request\">enhancement</span> <span data-mx-bg-color=\"#5012AA\" data-mx-color=\"#FFFFFF\">GitHub</span> <span data-mx-bg-color=\"#fc6d26\" data-mx-color=\"#000000\">GitLab</span>"
```
desktop:
![image](https://user-images.githubusercontent.com/2803622/148939554-c3df09df-bd7e-4d81-84ba-de80bb492e63.png)

android, really confused me:
![Screenshot_20220111-130615459 (1)](https://user-images.githubusercontent.com/2803622/148939820-6dccb9a4-8681-49ac-a4ab-693f57fe1493.jpg)

Is this specced properly and android is lagging behind badly? Otherwise or if possible this should be formatted such that it's intelligible without the color.

**Comment by Half-Shot** [comment]
It's specced, Android is lagging. https://spec.matrix.org/v1.1/client-server-api/#mroommessage-msgtypes
