### ISSUE TITLE
GitHub: Username that created issue isn't bold

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#153]
![image](https://user-images.githubusercontent.com/2803622/148999447-21a73ad8-d513-4550-b934-36fec4ecc15e.png)
![image](https://user-images.githubusercontent.com/2803622/148999471-c96fc202-1597-4b98-98ae-11108829c75f.png)
![image](https://user-images.githubusercontent.com/2803622/148999500-54cc5f32-7000-4370-8933-d94af30e94c5.png)

**Comment by Half-Shot** [comment]
Believed this is fixed in https://github.com/Half-Shot/matrix-hookshot/pull/141, does this work on latest?

**Comment by HarHarLinks** [comment]
No idea, I don't have a hookshot setup yet 😰
@github:half-shot.uk isn't bleeding edge then?

**Comment by Half-Shot** [comment]
Oh no, it only gets updates when it's lazy admin does it. I'm confident this is fixed, but will update my bridge later.
