### ISSUE TITLE
ability to manage which users are allowed to use the bridge instance

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#157]
Is bridge usage limited to the local homeserver? This or even tighter access control like lists/regex of individual users might be desirable for admins of small servers that don't wish to provide such a public service.

**Comment by Half-Shot** [comment]
This is basically https://github.com/Half-Shot/matrix-hookshot/issues/74

**Comment by HarHarLinks** [comment]
sorry, missed that
