### ISSUE TITLE
bump user-agent

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#172]
on latest docker as of now logs say:
`'user-agent': 'matrix-hookshot v0.0.1 octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/16.13.1 (linux; x64)'`

**Comment by Half-Shot** [comment]
I believe this got fixed in https://github.com/Half-Shot/matrix-hookshot/commit/7049802750ccf14e41638d680bb8ce5bfefc4899
