### ISSUE TITLE
Bridge fails on Announcement channels.

### ISSUE THREAD

**Issue by Miepee** [Half-Shot/matrix-hookshot#210]
Trying to setup the bridge on "Discord announcement channels" fails.
It waits a while before responding back with `There was a problem bridging that channel - has the guild owner approved the bridge?` even if it has Admin powers in the Discord Server.

**Comment by Half-Shot** [comment]
Hookshot does not bridge Discord, you likely have the wrong repo.

**Comment by Miepee** [comment]
I indeed have, sorry.
